def hello_list():
    greetings = (
        # Professional / Formal
        "Good morning",
        "Good afternoon",
        "Good evening",
        "Greetings",
        "Hello",
        "Welcome",
        "Pleased to meet you",
        "How do you do?",
        "It's a pleasure to meet you",
        "Salutations",
        "Respectful greetings",
        "I bid you hello",

        # Casual / Informal
        "Hi",
        "Hey",
        "Hey there",
        "Hiya",
        "Hello there",
        "Howdy",
        "What's up?",
        "How's it going?",
        "What's new?",
        "How are things?",
        "How have you been?",
        "What's happening?",
        "What's going on?",
        "How's everything?",
        "What's good?",
        "Heya",
        "Yo",
        "Alright?",
        "How's life?",

        # Slang / Colloquial
        "Sup",
        "Whassup?",
        "Yoohoo",
        "Aye",
        "Yo",
        "Wassup",
        "Howzit",  # South African English
        "G'day",   # Australian English
        "Heyyo",
        "Whatcha up to?",
        "How's it hanging?",
        "What's crackin'?",
        "What's poppin'?",
        "What's cookin'?",
        "How goes it?",
        "What's the haps?",
        "What's the dizzle?",  # Snoop Dogg-inspired

        # Regional / Cultural Variants
        "Top of the morning to you",  # Irish English
        "Alright?",                   # British English
        "How's tricks?",              # Older British English
        "How do?",                    # Northern England
        "Wotcha",                     # Cockney English
        "Hullo",                      # Old-fashioned / Quaint
        "Hi hi",                      # Playful / Childlike
        "Mornin'",                    # Shortened "Good morning"
        "Evenin'",                    # Shortened "Good evening"
        "Afternoon",                  # Shortened "Good afternoon"
        "Good day",                   # More formal, less common
        "Well, hello there",          # Playful, slightly formal
        "Look who it is!",            # Friendly, surprised
        "Long time, no see",          # Greeting someone not seen for a while
        "Greetings and salutations",  # Very formal or playful, depending on tone
    )

    return greetings

def prompt_list():
    prompts = (
        'How many',
        'What is',
        'Who is',
        'What are',
        'How is',
        'Why is',
        'Can you explain',
        'When did',
        'Where is',
        'List of',
        'Define',
        'Compare and contrast',
        'Explain the process of',
        'Describe the importance of',
        'Discuss the implications of',
        'Analyze the impact of',
        'Evaluate the effectiveness of',
        'Identify the key factors influencing',
        'Illustrate the relationship between',
        'Examine the correlation between',
        'Predict the outcome of',
        'Summarize',
        'Outline',
        'Determine the significance of',
        'Elaborate on',
        'Interpret',
        'Clarify',
        'Propose a solution for',
        'Suggest reasons for',
        'Explain how to',
        'Investigate',
        'Hypothesize about',
        'Conduct a study on',
        'Formulate a hypothesis for',
        'Justify',
        'Contrast',
        'Explore the possibilities of',
        'Investigate the effects of',
        'Argue for or against',
        'Discuss the advantages and disadvantages of',
        'Analyze the relationship between',
        'Illustrate with examples',
        'Predict the consequences of',
        'Identify the characteristics of',
        'Assess the validity of',
        'Evaluate the pros and cons of',
        'Demonstrate',
        'Explain the meaning of',
        'Interpret the data to',
        'Present evidence that',
        'Evaluate the impact of',
        'Critique',
        'Justify your choice of',
        'Discuss the similarities and differences between',
        'Evaluate the effectiveness of the strategy to',
        'Describe the process of',
        'Analyze the role of',
        'Evaluate the ethical implications of',
        'Explain the concept of',
        'Analyze the factors contributing to',
        'Discuss the implications of the findings on',
        'Predict the future of',
        'Evaluate the relevance of',
        'Examine the relationship between',
        'Evaluate the reliability of',
        'Discuss the potential solutions for',
        'Debate the merits of',
        'Examine the impact of technology on',
        'Analyze the trends in',
        'Critically evaluate',
        'Discuss the challenges facing',
        'Evaluate the feasibility of',
        'Examine the causes of',
        'Compare the approaches to',
        'Assess the impact of globalization on',
        'Critique the methodology used to',
        'Evaluate the benefits of',
        'Explain the limitations of',
        'Assess the implications of',
        'Analyze the effects of',
        'Evaluate the influence of culture on',
        'Discuss the future prospects of',
        'Evaluate the role of government in',
        'Assess the effectiveness of',
        'Discuss the consequences of',
        'Evaluate the impact of policy on',
        'Analyze the relationship between socioeconomic status and',
        'Explain the theories related to',
        'Evaluate the role of education in',
        'Analyze the impact of climate change on',
        'Discuss the potential benefits of',
        'Evaluate the impact of social media on',
        'Analyze the factors affecting',
        'Evaluate the relationship between poverty and',
        'Explain the mechanisms behind',
        'Analyze the implications of',
        'Evaluate the strategies for',
        'Discuss the impact of globalization on',
        'Evaluate the effectiveness of interventions for',
        'Analyze the impact of advertising on',
        'Discuss the relationship between diet and',
        'Evaluate the effectiveness of healthcare systems in',
        'Analyze the factors contributing to the rise of',
        'Evaluate the relationship between technology and',
        'Analyze the advantages and disadvantages of',
        'Evaluate the role of government in',
        'Analyze the relationship between income inequality and',
        'Evaluate the impact of environmental factors on',
        'Analyze the effects of urbanization on',
        'Evaluate the effectiveness of community programs for',
        'Analyze the factors influencing healthcare access for',
        'Evaluate the impact of poverty on',
        'Analyze the influence of peer pressure on',
        'Evaluate the effectiveness of interventions for',
        'Analyze the impact of globalization on',
        'Evaluate the effectiveness of educational initiatives for',
        'Analyze the factors influencing health outcomes for',
        'Evaluate the impact of discrimination on',
        'Analyze the implications of mental health stigma on',
        'Evaluate the effectiveness of public health campaigns for',
        'Analyze the impact of social determinants on',
        'Evaluate the relationship between socioeconomic status and',
        'Analyze the effects of lifestyle choices on',
        'Evaluate the impact of technology on',
        'Analyze the role of government policies in',
        'Evaluate the effectiveness of interventions for',
        'Analyze the impact of income inequality on',
        'Evaluate the relationship between healthcare access and',
        'Analyze the factors influencing health outcomes in',
        'Evaluate the impact of social support on',
        'Analyze the influence of healthcare policies on',
        'Evaluate the effectiveness of interventions targeting',
        'Analyze the impact of socioeconomic status on',
        'Evaluate the relationship between social determinants and',
        'Analyze the effects of discrimination on',
        'Evaluate the influence of cultural beliefs on',
        'Analyze the factors affecting access to healthcare for',
        'Evaluate the effectiveness of programs addressing',
        'Analyze the factors influencing health disparities in',
        'Evaluate the relationship between socioeconomic status in',
        'Analyze the effects of environmental factors in',
        'Evaluate the impact of technology in',
        'Analyze the role of government policies in',
        'Evaluate the effectiveness of interventions targeting',
        'Analyze the impact of globalization in',
        'Evaluate the implications of income inequality in',
        'Analyze the relationship between healthcare access in',
        'Evaluate the factors influencing health outcomes in',
        'Analyze the effects of social support in',
        'Evaluate the impact of cultural competence in',
        'Analyze the influence of healthcare policies in',
        'Evaluate the effectiveness of interventions addressing',
        'Analyze the impact of socioeconomic status in',
        'Evaluate the relationship between social determinants in',
        'Analyze the effects of discrimination in',
        'Evaluate the influence of cultural beliefs in',
        'Analyze the factors affecting access to healthcare in',
        'Evaluate the effectiveness of programs addressing',
        'Analyze the factors influencing health disparities among',
        'Evaluate the relationship between socioeconomic status and',
        'Analyze the effects of environmental factors on',
        'Evaluate the impact of technology on',
        'Analyze the role of government policies on',
        'Evaluate the effectiveness of interventions targeting',
        'Analyze the impact of globalization on',
        'Evaluate the implications of income inequality on',
        'Analyze the relationship between healthcare access and',
        'Evaluate the factors influencing health outcomes among',
        'Analyze the effects of social support on',
        'Evaluate the impact of cultural competence on',
        'Analyze the influence of healthcare policies on',
        'Evaluate the effectiveness of interventions for',
        'Analyze the impact of socioeconomic status on',
        'Evaluate the relationship between social determinants and',
        'Analyze the effects of discrimination on',
        'Evaluate the influence of cultural beliefs on',
        'Analyze the factors affecting access to healthcare for',
        'Evaluate the effectiveness of programs addressing',
        'Analyze the factors influencing health disparities in',
        'Evaluate the relationship between socioeconomic status and',
        'Analyze the effects of environmental factors on',
        'Evaluate the impact of technology on',
        'Analyze the role of government policies on',
        'Evaluate the effectiveness of interventions targeting',
        'Analyze the impact of globalization on',
        'Evaluate the implications of income inequality on',
        'Analyze the relationship between healthcare access and',
        'Evaluate the factors influencing health outcomes in',
        'Analyze the effects of social support on',
        'Evaluate the impact of cultural competence on',
        'Analyze the influence of healthcare policies on',
        'Evaluate the effectiveness of interventions for',
        'Analyze the impact of socioeconomic status on',
        'Evaluate the relationship between social determinants and',
        'Analyze the effects of discrimination on',
        'Evaluate the influence of cultural beliefs on',
        'Analyze the factors affecting access to healthcare for',
        'Evaluate the effectiveness of programs addressing',
        'Analyze the factors influencing health disparities in',
        'Evaluate the relationship between socioeconomic status and',
        'Analyze the effects of environmental factors on',
        'Evaluate the impact of technology on',
        'Analyze the role of government policies on',
        'Evaluate the effectiveness of interventions targeting',
        'Analyze the impact of globalization on',
        'Evaluate the implications of income inequality on',
        'Analyze the relationship between healthcare access and',
        'Evaluate the factors influencing health outcomes in',
        'Analyze the effects of social support on',
        'Evaluate the impact of cultural competence on',
        'Analyze the influence of healthcare policies on',
        'Evaluate the effectiveness of interventions for',
        'Analyze the impact of socioeconomic status on',
        'Evaluate the relationship between social determinants and',
        'Analyze the effects of discrimination on',
        'Evaluate the influence of cultural beliefs on',
        'Analyze the factors affecting access to healthcare for',
        'Evaluate the effectiveness of programs addressing',
        'Analyze the factors influencing health disparities in',
        'Evaluate the relationship between socioeconomic status and',
        'Analyze the effects of environmental factors on',
        'Evaluate the impact of technology on',
        'Analyze the role of government policies on',
        'Evaluate the effectiveness of interventions targeting',
        'Analyze the impact of globalization on',
        'Evaluate the implications of income inequality on',
        'Analyze the relationship between healthcare access and',
        'Evaluate the factors influencing health outcomes in',
        'Analyze the effects of social support on',
        'Evaluate the impact of cultural competence on',
        'Analyze the influence of healthcare policies on',
        'Evaluate the effectiveness of interventions for',
        'Analyze the impact of socioeconomic status on',
        'Evaluate the relationship between social determinants and',
        'Analyze the effects of discrimination on',
        'Evaluate the influence of cultural beliefs on',
        'Analyze the factors affecting access to healthcare for',
        'Evaluate the effectiveness of programs addressing',
        'Analyze the factors influencing health disparities in',
        'Evaluate the relationship between socioeconomic status and',
        'Analyze the effects of environmental factors on',
        'Evaluate the impact of technology on',
        'Analyze the role of government policies on',
        'Evaluate the effectiveness of interventions targeting',
        'Analyze the impact of globalization on',
        'Evaluate the implications of income inequality on',
        'Analyze the relationship between healthcare access and',
        'Evaluate the factors influencing health outcomes in',
        'Analyze the effects of social support on',
        'Evaluate the impact of cultural competence on',
        'Analyze the influence of healthcare policies on',
        'Evaluate the effectiveness of interventions for',
        'Analyze the impact of socioeconomic status on',
        'Evaluate the relationship between social determinants and',
        'Analyze the effects of discrimination on',
        'Evaluate the influence of cultural beliefs on',
        'Analyze the factors affecting access to healthcare for',
        'Evaluate the effectiveness of programs addressing',
        'Analyze the factors influencing health disparities in',
        'Evaluate the relationship between socioeconomic status and',
        'Analyze the effects of environmental factors on',
        'Evaluate the impact of technology on',
        'Analyze the role of government policies on',
        'Evaluate the effectiveness of interventions targeting',
        'Analyze the impact of globalization on',
        'Evaluate the implications of income inequality on',
        'Analyze the relationship between healthcare access and',
        'Evaluate the factors influencing health outcomes in',
        'Analyze the effects of social support on',
        'Evaluate the impact of cultural competence on',
        'Analyze the influence of healthcare policies on',
        'Evaluate the effectiveness of interventions for',
        'Analyze the impact of socioeconomic status on',
        'Evaluate the relationship between social determinants and',
        'Analyze the effects of discrimination on',
        'Evaluate the influence of cultural beliefs on',
        'Analyze the factors affecting access to healthcare for',
        'Evaluate the effectiveness of programs addressing',
        'Analyze the factors influencing health disparities in',
        'Evaluate the relationship between socioeconomic status and',
        'Analyze the effects of environmental factors on',
        'Evaluate the impact of technology on',
        'Analyze the role of government policies on',
        'Evaluate the effectiveness of interventions targeting',
        'Analyze the impact of globalization on',
        'Evaluate the implications of income inequality on',
        'Analyze the relationship between healthcare access and',
        'Evaluate the factors influencing health outcomes in',
        'Analyze the effects of social support on',
        'Evaluate the impact of cultural competence on',
        'Analyze the influence of healthcare policies on',
        'Evaluate the effectiveness of interventions for',
        'Analyze the impact of socioeconomic status on',
        'Evaluate the relationship between social determinants and',
        'Analyze the effects of discrimination on',
        'Evaluate the influence of cultural beliefs on',
        'Analyze the factors affecting access to healthcare for',
        'Evaluate the effectiveness of programs addressing',
        'Analyze the factors influencing health disparities in',
        'Evaluate the relationship between socioeconomic status and',
        'Analyze the effects of environmental factors on',
        'Evaluate the impact of technology on',
        'Analyze the role of government policies on',
        'Evaluate the effectiveness of interventions targeting',
        'Analyze the impact of globalization on',
        'Evaluate the implications of income inequality on',
        'Analyze the relationship between healthcare access and',
        'Evaluate the factors influencing health outcomes in',
        'Analyze the effects of social support on',
        'Evaluate the impact of cultural competence on',
        'Analyze the influence of healthcare policies on',
        'Evaluate the effectiveness of interventions for',
        'Analyze the impact of socioeconomic status on',
        'Evaluate the relationship between social determinants and',
        'Analyze the effects of discrimination on',
        'Evaluate the influence of cultural beliefs on',
        'Analyze the factors affecting access to healthcare for',
        'Evaluate the effectiveness of programs addressing',
        'Analyze the factors influencing health disparities in',
        'Evaluate the relationship between socioeconomic status and',
        'Analyze the effects of environmental factors on',
        'Evaluate the impact of technology on',
        'Analyze the role of government policies on',
        'Evaluate the effectiveness of interventions targeting',
        'Analyze the impact of globalization on',
        'Evaluate the implications of income inequality on',
        'Analyze the relationship between healthcare access and',
        'Evaluate the factors influencing health outcomes in',
        'Analyze the effects of social support on',
        'Evaluate the impact of cultural competence on',
        'Analyze the influence of healthcare policies on',
        'Evaluate the effectiveness of interventions for',
        'Analyze the impact of socioeconomic status on',
        'Evaluate the relationship between social determinants and',
        'Analyze the effects of discrimination on',
        'Evaluate the influence of cultural beliefs on',
        'Analyze the factors affecting access to healthcare for',
        'Evaluate the effectiveness of programs addressing',
        'Analyze the factors influencing health disparities in',
        'Evaluate the relationship between socioeconomic status and',
        'Analyze the effects of environmental factors on',
        'Evaluate the impact of technology on',
        'Analyze the role of government policies on',
        'Evaluate the effectiveness of interventions targeting',
        'Analyze the impact of globalization on',
        'Evaluate the implications of income inequality on',
        'Analyze the relationship between healthcare access and',
        'Evaluate the factors influencing health outcomes in',
        'Analyze the effects of social support on',
        'Evaluate the impact of cultural competence',
    )
    return prompts